# Generated by Django 4.2 on 2025-10-22 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_internalproduct_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='conceptproject',
            name='client_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
