# Generated by Django 4.2 on 2025-10-24 09:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_conceptproject_client_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conceptproject',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='conceptproject',
            name='external_recommendations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conceptproject',
            name='internal_recommendations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conceptproject',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='internalproduct',
            name='extracted_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='internalproduct',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='conceptproject',
            name='session_id',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='internalproduct',
            name='pdf_file',
            field=models.FileField(upload_to='products/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AddIndex(
            model_name='conceptproject',
            index=models.Index(fields=['session_id'], name='core_concep_session_8c2905_idx'),
        ),
    ]
