# Generated by Django 4.2 on 2025-10-27 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_conceptproject_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conceptproject',
            name='pre_preview_answers',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='conceptproject',
            name='pre_preview_questions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='conceptproject',
            name='uploaded_pdf_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
