# Generated by Django 4.2 on 2025-10-27 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_conceptproject_pre_preview_answers_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='internalproduct',
            options={'ordering': ['name']},
        ),
        migrations.RemoveIndex(
            model_name='conceptproject',
            name='core_concep_session_8c2905_idx',
        ),
        migrations.RemoveField(
            model_name='internalproduct',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='conceptproject',
            name='conversation_history',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='conceptproject',
            name='final_concept_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='conceptproject',
            name='formatted_preview',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='conceptproject',
            name='raw_input',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='conceptproject',
            name='session_id',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='internalproduct',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='products/'),
        ),
    ]
